import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Hero";
import styles from "../styles/Home.module.css";
import { API_URL } from "../ulits/url";
import Categories from "../components/Categories";
import About from "../components/About";
import Contact from "../components/ContactForm";

export default function Home({ categories }) {
  return (
    <div>
      <Head>
        <title>Entrepreneur Pages</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />

      <Categories categories={categories} />
      <About />
      <Contact />
    </div>
  );
}

export const getStaticProps = async () => {
  // Fetch Products
  const categories_res = await fetch(`${API_URL}/categories?_limit=8`);
  const categories = await categories_res.json();

  // return Products

  return {
    props: {
      categories,
      revalidate: 100,
    },
  };
};
